# Generated by Django 2.0.4 on 2018-05-08 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('zip', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('last_in', models.DateField()),
                ('folder_location', models.CharField(max_length=80)),
                ('needs_followup', models.BooleanField(default=False)),
                ('updated', models.DateField()),
                ('created', models.DateField()),
                ('last_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
