# Generated by Django 2.0.4 on 2018-05-08 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('QUOTE', 'QUOTE'), ('ORDER', 'ORDER'), ('COMPLETED', 'COMPLETED'), ('ARCHIVE', 'ARCHIVED')], max_length=10)),
                ('quote', models.IntegerField()),
                ('quote_date', models.DateField()),
                ('order_date', models.DateField()),
                ('due_date', models.DateField()),
                ('deposite', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('notes', models.TextField()),
                ('need_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('payment_due_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CustomerModel')),
            ],
        ),
    ]
