# Generated by Django 2.0.4 on 2018-05-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180511_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='oder_type',
            field=models.CharField(default='print', max_length=10),
        ),
    ]
