# Generated by Django 2.0.4 on 2018-05-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_printorder_oder_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printorder',
            old_name='oder_type',
            new_name='order_type',
        ),
    ]
