# Generated by Django 2.0.4 on 2018-05-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20180512_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printorder',
            name='order_type',
        ),
        migrations.AddField(
            model_name='abstractorder',
            name='order_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
