# Generated by Django 2.0.4 on 2018-05-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20180507_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='folder_location',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='last_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
