# Generated by Django 2.0.4 on 2018-05-14 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20180512_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignOrder',
            fields=[
                ('abstractorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.AbstractOrder')),
                ('quantity', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('material', models.CharField(max_length=40)),
                ('double_sided', models.BooleanField(default=False)),
                ('gromets', models.BooleanField(default=False)),
                ('sewing', models.BooleanField(default=False)),
                ('webbing', models.BooleanField(default=False)),
                ('tape', models.BooleanField(default=False)),
                ('corner_rounding', models.BooleanField(default=False)),
            ],
            bases=('backend.abstractorder',),
        ),
        migrations.AlterField(
            model_name='abstractorder',
            name='order_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
